### ISSUE TITLE
jsmi - Attacker can disable the `trustClaimers`.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-07-sense-points-marketplace-judging#10]
jsmi

Medium

# Attacker can disable the `trustClaimers`.

## Summary
Vault allows `receiver`(`trustedClaimers`) to claim `PTokens` on behalf of `account`.
Attacker can front-run `receiver`'s claim tx and can always trasfer `PTokens` to original `account` not to `receiver`(`trustedClaimers`).
## Vulnerability Detail
The relevant code of `PointTokenVault.claimPTokens()` is following.
```solidity
    function claimPTokens(Claim calldata _claim, address _account, address _receiver) public {
        bytes32 pointsId = _claim.pointsId;

        bytes32 claimHash = keccak256(abi.encodePacked(_account, pointsId, _claim.totalClaimable));
        _verifyClaimAndUpdateClaimed(_claim, claimHash, _account, claimedPTokens);

        if (address(pTokens[pointsId]) == address(0)) {
            revert PTokenNotDeployed();
        }

152     if (_account != _receiver && !trustedClaimers[_account][_receiver]) {
            revert NotTrustedClaimer();
        }

        uint256 pTokenFee = FixedPointMathLib.mulWadUp(_claim.amountToClaim, mintFee);
        pTokenFeeAcc[pointsId] += pTokenFee;

        pTokens[pointsId].mint(_receiver, _claim.amountToClaim - pTokenFee); // Subtract mint fee.

        emit PTokensClaimed(_account, _receiver, pointsId, _claim.amountToClaim, pTokenFee);
    }
```
If `_receiver` differs with `_account`, `_receiver` should be trusted beforehand by the following `trustClaimer()`.
```solidity
    function trustClaimer(address _account, bool _isTrusted) public {
        trustedClaimers[msg.sender][_account] = _isTrusted;
        emit TrustClaimer(msg.sender, _account, _isTrusted);
    }
```
Then the following attack path is available.
1. `_account` trusts `_receiver` by calling `trustClaimer(_receiver, true)`.
2. `_receiver` calls `claimPTokens(claim, _account, _receiver)` to receive `PTokens`.
3. Attacker front-runs `_receiver`'s claim tx by calling `claimPTokens(claim, _account, _account)` to transfers `PTokens` to `_account`.
4. `_receiver`'s tx will be reverted because all `PTokens` are already transferred to `_account`.
5. As a result, attacker can prevent `_receiver` from transferring `PTokens` to `_receiver`.

## Impact
Attacker can prevent `_receiver` from transferring `PTokens` to `_receiver` or original `_account` from transferring `PTokens` to himself. That is, attacker can disable the core function of contract and damage the reputation of the protocol.

In general, this issue doesn't cause loss of funds because the `PTokens` are transferred to original account and can be transferred again to `receiver` manually. However, if `_account` is a smart contract and the contract has no function to transfer `PTokens`, the tokens may be locked there.

## Code Snippet
- [PointTokenVault.claimPTokens()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L142-L162)

## Tool used

Manual Review

## Recommendation
It is recommeded to add authority check in `PointTokenVault.claimPTokens()`.
```diff
    function claimPTokens(Claim calldata _claim, address _account, address _receiver) public {
        bytes32 pointsId = _claim.pointsId;

        bytes32 claimHash = keccak256(abi.encodePacked(_account, pointsId, _claim.totalClaimable));
        _verifyClaimAndUpdateClaimed(_claim, claimHash, _account, claimedPTokens);

        if (address(pTokens[pointsId]) == address(0)) {
            revert PTokenNotDeployed();
        }
        
+       if (msg.sender != _account && msg.sender != _receiver) {
+           revert;
+       }
        if (_account != _receiver && !trustedClaimers[_account][_receiver]) {
            revert NotTrustedClaimer();
        }

        uint256 pTokenFee = FixedPointMathLib.mulWadUp(_claim.amountToClaim, mintFee);
        pTokenFeeAcc[pointsId] += pTokenFee;

        pTokens[pointsId].mint(_receiver, _claim.amountToClaim - pTokenFee); // Subtract mint fee.

        emit PTokensClaimed(_account, _receiver, pointsId, _claim.amountToClaim, pTokenFee);
    }
```

Duplicate of #147

**Comment by jsmi0703** [comment]
Please give me detailed reason of "Sponsor Disputed".
