### ISSUE TITLE
novaman33 - Fee on transfer tokens will create insolvency in `PointTokenVault.sol`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-07-sense-points-marketplace-judging#15]
novaman33

High

# Fee on transfer tokens will create insolvency in `PointTokenVault.sol`

## Summary
In the readMe it is stated that fee on transfer tokens will be supported. However due to wrong accounting they will likely create insolvency.
## Vulnerability Detail
When a user calls deposit, the balance that the contract will actually have will be less than what is being set in `balances`. As a result if everybody calls withdraw the assets will not be enough to satisfy everyone's withdraw.
## Impact
Protocol insolvency - High
## Code Snippet
https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/076bf833f4dc1418e93c8172e4a4110344f1c812/point-tokenization-vault/contracts/PointTokenVault.sol#L125
## Tool used

Manual Review

## Recommendation
Track the balance before and after the transfer in the deposit function and calculate the balance delta in order to account for the fees.

**Comment by novaman33** [comment]
Escalate,
these tokens are supported per readMe. I do not know why it was invalidated.

**Comment by sherlock-admin3** [comment]
> Escalate,
> these tokens are supported per readMe. I do not know why it was invalidated.
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by amankakar** [comment]
> > Escalate,
> > these tokens are supported per readMe. I do not know why it was invalidated.
> 
> You've created a valid escalation!
> 
> To remove the escalation from consideration: Delete your comment.
> 
> You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

I think this comment will answer your question :
 [ // Rebasing and fee-on-transfer tokens must be wrapped before depositing](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/076bf833f4dc1418e93c8172e4a4110344f1c812/point-tokenization-vault/contracts/PointTokenVault.sol#L113C1-L114C1).

**Comment by WangSecurity** [comment]
The comment above is correct, based on the code comment I believe it's known is function is not working properly with rebasing and fee-on-transfer tokens. Hence, planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [novaman33](https://github.com/sherlock-audit/2024-07-sense-points-marketplace-judging/issues/15/#issuecomment-2326145176): rejected
