### ISSUE TITLE
fibonacci - Rumpel Module allows arbitrary ETH transfer from user wallets

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-07-sense-points-marketplace-judging#153]
fibonacci

High

# Rumpel Module allows arbitrary ETH transfer from user wallets

## Summary
The authorized actor on the Rumpel Module can pass a `value` to the `Call` parameter and transfer ETH from user wallets to an arbitrary address.

## Vulnerability Detail
The Rumpel Module allows the protocol to take actions on behalf of a user. It needs to be able to automatically claim reward tokens after an external protocol releases them and transfer the reward tokens to the Point Tokenization Vault.

To restrict which actions can be taken, the Rumpel Module also includes an irreversible blacklist.

```solidity
mapping(address => mapping(bytes4 => bool)) public blockedModuleCalls; // target => functionSelector => blocked
```

So all calls to added address-selector pairs are blocked.

According to the documentation, this is done to prevent the actor from accessing funds in the user's wallet (e.g., transferring a user's USDC).

However, executing a call with the `value` parameter passed into the `execTransactionFromModule` function allows sending ETH along with the call. Crucially, this action cannot be blocked because the recipient address can be specified arbitrarily, rendering it impossible to block all possible addresses.

## Impact
A malicious or compromised actor could potentially drain all the ETH from all Rumpel Wallets.

## Code Snippet
https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/rumpel-wallet/src/RumpelModule.sol#L52

## Tool used

Manual Review

## Recommendation
The module does not need to be able to transfer ETH to fulfil its functions (claim and transferring rewards tokens). 

```diff
- bool success = call.safe.execTransactionFromModule(call.to, call.value, call.data, call.operation);
+ bool success = call.safe.execTransactionFromModule(call.to, 0, call.data, call.operation);
```

**Comment by 0xf1b0** [comment]
Escalate

I believe it's a valid issue. Both the code and docs tell us that the role of the module owner is partially trusted and if we see protection against user tokens transfers, there should definitely be protection against ETH transfers.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> I believe it's a valid issue. Both the code and docs tell us that the role of the module owner is partially trusted and if we see protection against user tokens transfers, there should definitely be protection against ETH transfers.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
@0xf1b0 could you elaborate more on this role being partially trusted, could you forward me to the exact part of the docs and help me understand how they're (module owner) set inside the code?

**Comment by 0xf1b0** [comment]
@WangSecurity for sure.
1.  The [README](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/README.md?plain=1#L62) emphasizes that the module owner's authority poses a significant risk:
> The authorized actor on the Rumpel module can execute arbitrary actions on behalf of Rumpel Wallets. It is known that this is a risk.

2. In the code [here](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/rumpel-wallet/src/RumpelModule.sol#L69) and [here](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/rumpel-wallet/src/RumpelModule.sol#L42) we can see a blacklist approach to restricted sets of actions that are allowed for the owner. This also means that the owner cannot be completely trusted.

3. The code [comments](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/rumpel-wallet/src/RumpelModule.sol#L66) are quite explicit about the fact that the owner should not have access to the user's funds:.
> Prevent call from being executed via the module permanently. Useful as an assurance that e.g. an admin will never transfer a user's USDC.

**Comment by 0xf1b0** [comment]
Also in the [code](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/rumpel-wallet/src/RumpelGuard.sol#L70-L74), we can see that transactions with ETH are supposed to be performed from the wallet.

On the [diagram](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/assets/point-tokenization-system.png), we see that it is assumed to work with protocols that allow staking ETH and getting rewards (e.g., rsETH, eETH).

At the same time, I personally do not know any protocol that issues rewards in ETH, so there is no reason for allowing the owner of the module to have access to them.

So, leaving this code is simply a backdoor.

**Comment by jsmi0703** [comment]
> The authorized actor on the Rumpel module can execute arbitrary actions on behalf of Rumpel Wallets. It is known that this is a risk.

According to readme, the above sentence is the known and acceptable issue. It means that authorized actor should be trusted.

**Comment by WangSecurity** [comment]
> The [README](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/README.md?plain=1#L62) emphasizes that the module owner's authority poses a significant risk

That doesn't mean the role is untrusted and it can be said basically about the owner of any contract in any protocol. Moreover, as said above, this is a known risk that an admin can execute arbitrary actions.

As for other 2 arguments, they're fair, but still they're not explicit that the role can be viewed as untrusted and this is a known risk as said above.

Hence, planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xf1b0](https://github.com/sherlock-audit/2024-07-sense-points-marketplace-judging/issues/153/#issuecomment-2327844522): rejected
