### ISSUE TITLE
0xnbvc - Incorrect Calculation of `pTokens` for Non-18 Decimal `rewardTokens`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-07-sense-points-marketplace-judging#155]
0xnbvc

High

# Incorrect Calculation of `pTokens` for Non-18 Decimal `rewardTokens`

## Summary

The `convertRewardsToPTokens()` function assumes all `rewardTokens` have 18 decimals, which leads to incorrect minting of `pTokens` when dealing with tokens that have fewer decimals.

## Vulnerability Detail

[The sponsor confirmed](https://discord.com/channels/812037309376495636/1277643765133348956/1278664773449289823) that `rewardTokens` could be "any non-weird ERC20 token":

> Watson: Reward tokens can be pretty much any non-weird ERC20 token right?
> Sponsor: Yes

The function `convertRewardsToPTokens()` uses `FixedPointMathLib::divWadDown()` to calculate the number of `pTokens` to mint:

[PointTokenVault.sol#L244](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/076bf833f4dc1418e93c8172e4a4110344f1c812/point-tokenization-vault/contracts/PointTokenVault.sol#L244)
```solidity
uint256 pTokensToMint = FixedPointMathLib.divWadDown(_amountToConvert, rewardsPerPToken); // Round down for mint.
```

This calculation assumes both `_amountToConvert` and `rewardsPerPToken` are in 18 decimal precision. However, if the reward token has fewer decimals (e.g., 6 decimals like USDC), this calculation will result in an incorrect number of `pTokens` being minted.

## Impact

Users can mint significantly more `pTokens` than intended when converting reward tokens with fewer than 18 decimals. Incompatibility with non-18 decimals `rewardTokens`.

## Code Snippet

[PointTokenVault.sol#L244](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/076bf833f4dc1418e93c8172e4a4110344f1c812/point-tokenization-vault/contracts/PointTokenVault.sol#L244)

## Tool used

Manual Review

## Recommendation

Adjust the calculation to account for the actual decimals of the reward token:

```solidity
uint256 decimals = rewardToken.decimals();
uint256 scaleFactor = 10**(18 - decimals);
uint256 pTokensToMint = FixedPointMathLib.divWadDown(_amountToConvert * scaleFactor, rewardsPerPToken);
```

This scales up the `_amountToConvert` to 18 decimals before performing the division, ensuring correct calculation regardless of the reward token's decimals.

**Comment by jparklev** [comment]
PR fix: https://github.com/sense-finance/point-tokenization-vault/pull/35

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/sense-finance/point-tokenization-vault/pull/35

**Comment by 0xHuntoor** [comment]
Escalate

in readMe
> Q: If you are integrating tokens, are you allowing only whitelisted tokens to work with the codebase or any complying with the standard? Are they assumed to have certain properties, e.g. be non-reentrant? Are there any types of [weird tokens](https://github.com/d-xo/weird-erc20) you want to integrate?
Yes, whitelisted tokens only. They're assumed to not be reentrant, but fee-on-transfer, pausable, and blocklist tokens are OK.

no mentions of low decimals, then the second source of truth is the code comments

to reply to this part of report
> This calculation assumes both _amountToConvert and rewardsPerPToken are in 18 decimal precision. However, if the reward token has fewer decimals (e.g., 6 decimals like USDC), this calculation will result in an incorrect number of pTokens being minted.

```solidity
File: PointTokenVault.sol
61:     struct RedemptionParams {
62:         ERC20 rewardToken;
63:         uint256 rewardsPerPToken; // Assume 18 decimals.
64:         bool isMerkleBased;
65:     }
```

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> in readMe
> > Q: If you are integrating tokens, are you allowing only whitelisted tokens to work with the codebase or any complying with the standard? Are they assumed to have certain properties, e.g. be non-reentrant? Are there any types of [weird tokens](https://github.com/d-xo/weird-erc20) you want to integrate?
> Yes, whitelisted tokens only. They're assumed to not be reentrant, but fee-on-transfer, pausable, and blocklist tokens are OK.
> 
> no mentions of low decimals, then the second source of truth is the code comments
> 
> to reply to this part of report
> > This calculation assumes both _amountToConvert and rewardsPerPToken are in 18 decimal precision. However, if the reward token has fewer decimals (e.g., 6 decimals like USDC), this calculation will result in an incorrect number of pTokens being minted.
> 
> ```solidity
> File: PointTokenVault.sol
> 61:     struct RedemptionParams {
> 62:         ERC20 rewardToken;
> 63:         uint256 rewardsPerPToken; // Assume 18 decimals.
> 64:         bool isMerkleBased;
> 65:     }
> ```

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by KupiaSecAdmin** [comment]
Escalate
This issue undoubtedly results in significant financial losses, warranting a classification of high severity.

# Another comment

@IlIlHunterlIlI

It is pointed nowhere that only Non-18 decimal tokens are whitelisted. For example, USDC is clearly whitelisted from README.
> Includes the ability to permanently allow a call, e.g. USDC.transfer, to give guarantees around which actions a user will always be able to take with their Safe.

You misunderstood the comment at L63; it clarifies that the decimal for the rewards rate is 18, rather than that of the reward assets.
> File: PointTokenVault.sol
> 61:       struct RedemptionParams {
> 62:             ERC20 rewardToken;
> 63:             uint256 rewardsPerPToken; // Assume 18 decimals.
> 64:             bool isMerkleBased;
> 65:       }

**Comment by sherlock-admin3** [comment]
> Escalate
> This issue undoubtedly results in significant financial losses, warranting a classification of high severity.
> 
> # Another comment
> 
> @IlIlHunterlIlI
> 
> It is pointed nowhere that only Non-18 decimal tokens are whitelisted. For example, USDC is clearly whitelisted from README.
> > Includes the ability to permanently allow a call, e.g. USDC.transfer, to give guarantees around which actions a user will always be able to take with their Safe.
> 
> You misunderstood the comment at L63; it clarifies that the decimal for the rewards rate is 18, rather than that of the reward assets.
> > File: PointTokenVault.sol
> > 61:       struct RedemptionParams {
> > 62:             ERC20 rewardToken;
> > 63:             uint256 rewardsPerPToken; // Assume 18 decimals.
> > 64:             bool isMerkleBased;
> > 65:       }

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0xHuntoor** [comment]
Audit readMe mentioned in my escalation override everything:

It describes the whitelisted Tokens as:
> They're assumed to not be reentrant, but fee-on-transfer, pausable, and blocklist tokens are OK.

They included **_fee-on-transfer, pausable, and blocklist_** and no mention of Low Decimals

To reply to this part
> USDC is clearly whitelisted from README.

your quoted readMe is the protocol readMe and not the audit readme
- the mentioned part is saying an example and took USDC as an example cause its very common between users
- -  this is clearly shown by the **eg.**
- that part of the readMe is for users and not for auditors, hence they don't override the rule of admin actions setting the whitelisted tokens that don't cause any harm plus the fact that USDC in audit readMe is OOS

**Secondly**:
> You misunderstood the comment at L63; it clarifies that the decimal for the rewards rate is 18, rather than that of the reward assets.

I may have agreed if the rate was a time rate, but the rate is reward/token not reward/second, and this fact should be considered

**Comment by Schereo** [comment]
> You misunderstood the comment at L63; it clarifies that the decimal for the rewards rate is 18, rather than that of the reward assets.

L63 clearly states that the `rewardsPerPToken` should be in 18 decimals but does not state anything about the decimals of the reward token. You can have `rewardsPerToken` be in 18 decimals and have a reward token that is non-18-decimals if you do proper conversion. So deriving from the statement that the reward token has to be 18 decimals because the conversion rate is 18 decimals, doesn't really make sense.


Second, even 17 or 19 decimals reward tokens will cause to many paid out rewards or no rewards at all because `pTokensToBurn` will be misscalculated:

> uint256 pTokensToBurn = FixedPointMathLib.divWadUp(amountToClaim, rewardsPerPToken);

**Comment by amankakar** [comment]
> > Escalate
> > in readMe
> > > Q: If you are integrating tokens, are you allowing only whitelisted tokens to work with the codebase or any complying with the standard? Are they assumed to have certain properties, e.g. be non-reentrant? Are there any types of [weird tokens](https://github.com/d-xo/weird-erc20) you want to integrate?
> > > Yes, whitelisted tokens only. They're assumed to not be reentrant, but fee-on-transfer, pausable, and blocklist tokens are OK.
> > 
> > 
> > no mentions of low decimals, then the second source of truth is the code comments
> > to reply to this part of report
> > > This calculation assumes both _amountToConvert and rewardsPerPToken are in 18 decimal precision. However, if the reward token has fewer decimals (e.g., 6 decimals like USDC), this calculation will result in an incorrect number of pTokens being minted.
> > 
> > 
> > ```solidity
> > File: PointTokenVault.sol
> > 61:     struct RedemptionParams {
> > 62:         ERC20 rewardToken;
> > 63:         uint256 rewardsPerPToken; // Assume 18 decimals.
> > 64:         bool isMerkleBased;
> > 65:     }
> > ```
> 
> You've created a valid escalation!
> 
> To remove the escalation from consideration: Delete your comment.
> 
> You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

Upon inquiring about the `uint256 rewardsPerPToken; // Assume 18 decimals`. from the Sponsor, they clarified that it has nothing to do with the reward token's decimals.

Q: what would you assume by blacklist tokens?

**Comment by WangSecurity** [comment]
Firstly, let's clarify the contest README, as quoted above, the answer is that tokens with fee-on-transfer, pausing and blacklisting functionality is applied. It doesn't talk about exact tokens and I believe it's a false assumption that if USDC has blacklist mechanism, then it's in-scope and low-decimals are in-scope as well. Hence, I believe we should consider low-decimal tokens do be OOS.

Secondly, several comments above are correct, the `rewardsPerToken` can be 18 decimals without the reward token having 18 decimals. Hence, for this to be non-18 decimals, it would be an admin mistake.

Based on the above two arguments, I believe it should be invalid, planning to accept @IlIlHunterlIlI escalation and reject @KupiaSecAdmin escalation.

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.

**Comment by KupiaSecAdmin** [comment]
@WangSecurity

Thank you for your prompt response, but I cannot agree that this issue should be viewed as an administrative mistake.

The README states that reentrant tokens are not utilized, but it does not mention anything about low-decimal tokens. 
> They're assumed to not be reentrant, but fee-on-transfer, pausable, and blocklist tokens are OK.

README also says that:
>Includes the ability to permanently allow a call, e.g. USDC.transfer, to give guarantees around which actions a user will always be able to take with their Safe.

Based on the previous comments, it is clear that USDC is intended to be whitelisted. Furthermore, if all non-18 decimal tokens are blacklisted, the protocol will be unable to support systems that utilize these tokens as additional rewards for utility points. This could lead to further negative consequences.

I kindly request that you reconsider this issue. 

Thank you.

**Comment by amankakar** [comment]
> Yes, whitelisted tokens only. They're assumed to not be reentrant, but fee-on-transfer, pausable, and blocklist tokens are OK.

To support this, we rely on the examples of fee-on-transfer, pausable, and blocklist tokens mentioned by Sherlock in their [weird-erc20](https://github.com/d-xo/weird-erc20).

The "weird token" example for [BlockList Token](https://github.com/d-xo/weird-erc20?tab=readme-ov-file#tokens-with-blocklists) includes USDC and USDT, which are non-18 decimals. Therefore, we must adhere to the guidelines and references provided in the Sherlock rule and contest readme.

All their documentation is filled with examples using USDC. If any Watson has reviewed their docs, they would definitely have noticed this issue.

**Comment by WangSecurity** [comment]
> Thank you for your prompt response, but I cannot agree that this issue should be viewed as an administrative mistake.
The README states that reentrant tokens are not utilized, but it does not mention anything about low-decimal tokens

Exactly, low decimals are not mentioned. Hence, we shouldn't assume the contracts are ready to comply with low-decimal tokens. In the same way, rebasing tokens are not mentioned, which also means we shouldn't consider rebasing tokens to be handled. 

> README also says that:

As I understand, that is the protocol's README, not the contest's README (i.e. the QA from [here](https://audits.sherlock.xyz/contests/494)), or I'm blind and don't see this line in there, excuse me if it's the case.

> Based on the previous comments, it is clear that USDC is intended to be whitelisted. Furthermore, if all non-18 decimal tokens are blacklisted, the protocol will be unable to support systems that utilize these tokens as additional rewards for utility points. This could lead to further negative consequences.

Still, non-decimal tokens are not integrated into the protocol, based on the contest's README. Hence, we should consider them out of scope.

> To support this, we rely on the examples of fee-on-transfer, pausable, and blocklist tokens mentioned by Sherlock in their [weird-erc20](https://github.com/d-xo/weird-erc20).
The "weird token" example for [BlockList Token](https://github.com/d-xo/weird-erc20?tab=readme-ov-file#tokens-with-blocklists) includes USDC and USDT, which are non-18 decimals. Therefore, we must adhere to the guidelines and references provided in the Sherlock rule and contest readme.

These are only the examples, they're the most famous ones, but I'm afraid not the only ones. Moreover, as I've said previously:
> it's a false assumption that if USDC has blacklist mechanism, then it's in-scope and low-decimals are in-scope as well

Moreover, as I understand from the discussion above and as I've said in the previous comment:
> Secondly, several comments above are correct, the rewardsPerToken can be 18 decimals without the reward token having 18 decimals. Hence, for this to be non-18 decimals, it would be an admin mistake

The `rewardsPerToken` is not connected to the reward token decimals and it can be 18 decimals if the reward token doesn't have 18 decimals. But, even if this assumption is wrong, still we have to assume low-decimal tokens are out of scope.

The decision remains. Planning to accept the escalation and invalidate the issue.

**Comment by KupiaSecAdmin** [comment]
@WangSecurity
The use of non-18 decimal tokens does not contradict the contest README; it only addresses the reentrant token issue, not the non-18 decimal aspect. Therefore, the decision to use USDC should be based on the protocol README, which indicates that USDC is utilized in this protocol.
> As I understand, that is the protocol's README, not the contest's README (i.e. the QA from here),

If a non-decimal token is intended for use, this issue should not be considered an administrative matter. For instance, in other contests, the statement 'USDT is supported' is deemed valid. Therefore, I believe this issue is indeed valid. 

Thank you.

**Comment by amankakar** [comment]
Could you please point out where in the readme it states that non-18 decimal tokens are not supported? As a security researcher, our role is to consider all edge cases not only the default ones, and I believe it's not reasonable to assume that only 18-decimal tokens will be used unless explicitly mentioned in the readMe.

The sponsor's intention appears to be clear that they intend to support non-18 decimal tokens, and they have also added the fix , I know that the sponsor fix will not make any issue valid here in sherlock (which is very sad in some cases), but I am focusing on the intention behind the support for non-18 decimal tokens and the potential for loss of funds in such cases. For these reasons,I believe this should be considered a valid finding.

**Comment by WangSecurity** [comment]
Thank you for these questions, but for the weird trait to be considered, it has to be explicitly mentioned in the contest README and that was always the case as you can see from the rule:
> Non-Standard tokens: Issues related to tokens with non-standard behaviors, such as [weird-tokens](https://github.com/d-xo/weird-erc20) are not considered valid by default unless these tokens are explicitly mentioned in the README

Tokens that have low decimals are not mentioned in the README explicitly (contest README, protocol's README is not taken into account here). Any tokens with <18 decimals or at least this trait are not mentioned in the README.

Hence, the decision remains, accept the escalation and invalidate the issue.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [IlIlHunterlIlI](https://github.com/sherlock-audit/2024-07-sense-points-marketplace-judging/issues/155/#issuecomment-2327861036): accepted
- [KupiaSecAdmin](https://github.com/sherlock-audit/2024-07-sense-points-marketplace-judging/issues/155/#issuecomment-2330485625): rejected

**Comment by WangSecurity** [comment]
UPD:
excuse me for missing the second escalation. To make it clear, @IlIlHunterlIlI escalation will be accepted, @KupiaSecAdmin escalation will be rejected and the issue will be invalidated.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

Also, wanted to ask Watsons, in these cases where you see that the protocol clearly wants to integrate the token out of scope, please contact me during the contest, so we can sort this out.

**Comment by amankakar** [comment]
Yeah sure, next time I will definitely reach you

**Comment by davies0212** [comment]
Hi @WangSecurity,

I reached out to the sponsor regarding the non-18 decimal reward tokens during the contest through a private thread. The sponsor confirmed that there is no assumption that the reward tokens must have 18 decimals.

I believe invalidating this issue is not fair.

**Comment by Schereo** [comment]
@davies0212 do you got any proof of that?

**Comment by davies0212** [comment]
I used a private thread, but it has been deleted.

**Comment by amankakar** [comment]
That proof doesn't matter, because Sherlock does not accept dm messages as
a proof

**Comment by davies0212** [comment]
If all weird tokens are assumed not to be whitelisted, then the following comment holds no significance.

> They're assumed to not be reentrant

Although reentrant tokens are quite weird, the README has clarified this.

> Yes, whitelisted tokens only. They're assumed to not be reentrant, but fee-on-transfer, pausable, and blocklist tokens are OK.

Therefore, it is assumed that non-18 decimal tokens can also be utilized. Additionally, the Protocol README states:

> Includes the ability to permanently allow a call, e.g. USDC.transfer, to give guarantees around which actions a user will always be able to take with their Safe.

This example clearly indicates that USDC is intended for use. Therefore, I don't understand why this issue should be dismissed as invalid.

**Comment by KupiaSecAdmin** [comment]
@WangSecurity

Thank you for your reply, but I must respectfully disagree with your subsequent statement.

> Tokens that have low decimals are not mentioned in the README explicitly (contest README, protocol's README is not taken into account here). Any tokens with <18 decimals or at least this trait are not mentioned in the README.

The contest README does not mention low decimal tokens; however, it does provide the URLs for two protocol READMEs.

(contest README)
> Please list any relevant protocol resources.
> The two READMEs are the best resources.
> Vault: https://github.com/sense-finance/point-tokenization-vault/blob/dev/README.md
> Wallet: https://github.com/sense-finance/rumpel-wallet/blob/main/README.md

In the second url(https://github.com/sense-finance/rumpel-wallet/blob/main/README.md), we can see the following sentence.
> Restricts wallet actions to specific admin-allowed <address>.<functionSelector> calls.
> Includes the ability to permanently allow a call, e.g. USDC.transfer, to give guarantees around which actions a user will always be able to take with their Safe.

It is clear that USDC is intended to serve as a reward token within this protocol. Additionally, USDC was referenced as an example of a reward in the previous audit, and the URL for that audit is included in the contest README. Therefore, I believe these statements should be considered part of the contest README.

I kindly ask you to reconsider this issue.

Thank you.

**Comment by WangSecurity** [comment]
Still, based on the contest README low decimals are **out of scope** because they're not explicitly mentioned there. Hence, any other source mentioning this as in-scope conflicts the contest README. In that situation, the contest README stands above all. Therefore, the non 18-decimal tokens are assumed out of scope.

**Comment by KupiaSecAdmin** [comment]
@WangSecurity

> Still, based on the contest README low decimals are out of scope because they're not explicitly mentioned there. Hence, any other source mentioning this as in-scope conflicts the contest README.

Low deciaml tokens are not explicitely mentioned in the contest README. 
However, I do not see any conflicts regarding the use of USDC:

1. It states that reentrant tokens are not permitted, which does not conflict with the use of USDC.
2. It also mentions that fee-on-transfer, pausable, and blocklist tokens are OK. Since USDC is a blocklist token, this statement actually supports its use.

The explanation regarding the weird tokens in the contest README is insufficient. Therefore, I believe we can rely on the protocol README as a basis.
