### ISSUE TITLE
araj - No withdraw function for `withdrawing` native ETH

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-07-sense-points-marketplace-judging#30]
araj

Medium

# No withdraw function for `withdrawing` native ETH

## Summary
No withdraw function for `withdrawing` native ETH

## Vulnerability Detail
There is `receive()` in pointsTokenVault.sol contract, which means protocol is `expected` to receive native ETH & also there is a test in pointsTokenVault.t.sol file, which tests sending native ETH in the contract.
```solidity
    contract PointTokenVault is UUPSUpgradeable, AccessControlUpgradeable, MulticallUpgradeable {
         ....
         receive() external payable {}
    }
```
```solidity
function test_ReceiveETH() public payable {
        // Amount of ETH to send
        uint256 amountToSend = 1 ether;

        // Record the initial balance of the PointTokenVault
        uint256 initialBalance = address(pointTokenVault).balance;

        // Send ETH to the PointTokenVault
        (bool sent,) = address(pointTokenVault).call{value: 1 ether}("");
        require(sent, "Failed to send Ether");

        // Check the new balance of the PointTokenVault
        uint256 newBalance = address(pointTokenVault).balance;
        assertEq(newBalance, initialBalance + amountToSend);
    }
```

But the problem is, there is no withdraw function that allow admin/owner to withdraw that native ETH

## Impact
ETH will stuck in the contract forever

## Code Snippet
https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L382
https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/test/PointTokenVault.t.sol#L766C1-L781C1

## Tool used
Manual Review

## Recommendation
Make a withdraw function that allow admin/owner to withdraw those ETH

**Comment by 0xAraj** [comment]
Escalate

I think this is valid medium as the report clearly shows vault can receive native ETH & also there is proper test in the test file, which tests vault can receive ETH, But there is no way to remove it

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> I think this is valid medium as the report clearly shows vault can receive native ETH & also there is proper test in the test file, which tests vault can receive ETH, But there is no way to remove it

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
As I understand, the protocol is not intended to receive ETH (the existence of the receive function is not an evidence), hence, just sending the ETH directly into the contract is a user mistake.

Hence, the lead judge is correct and the report has to remain invalid, planning to reject the escalation.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xAraj](https://github.com/sherlock-audit/2024-07-sense-points-marketplace-judging/issues/30/#issuecomment-2330596528): rejected
