### ISSUE TITLE
AuditorPraise - `RumpelGuard.checkAfterExecution()` lacks logic to catch failed transactions

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-07-sense-points-marketplace-judging#79]
AuditorPraise

Medium

# `RumpelGuard.checkAfterExecution()` lacks logic to catch failed transactions

## Summary
checkAfterExecution() is supposed to ensure the success of transaction in most cases due to safeTxGas || gasPrice not being == 0 BUT it doesn't.
## Vulnerability Detail
GnosisSafe uses Guards to ensure transactions go smoothly by calling into the Guard before and after execution.

Now the issue here lies in `RumpelGuard.checkAfterExecution()` which has no logic at all.
```solidity
    /// @notice Called by the Safe contract after a transaction is executed.
    /// @dev No-op.
    function checkAfterExecution(bytes32, bool) external view {}
```

Considering that `safeTxGas` and `gasPrice` will most likely be calculated and supplied via the frontend like e.g how metamask  does its own too, check to ensure success of transaction will be ineffective and `RumpelGuard.checkAfterExecution()` will fail to catch it.
```solidity
            require(success || safeTxGas != 0 || gasPrice != 0, "GS013");
```

Now the failed transaction is passed to `RumpelGuard.checkAfterExecution()` but it has no logic to revert the tx
```solidity
            if (guard != address(0)) {
                Guard(guard).checkAfterExecution(txHash, success);
            }
```
https://github.com/safe-global/safe-smart-account/blob/767ef36bba88bdbc0c9fe3708a4290cabef4c376/contracts/GnosisSafe.sol#L190-L192

## Impact
Possible Loss of funds due to contracts updating state even when the transaction fails because it thinks the tx was successful

## Code Snippet
https://github.com/safe-global/safe-smart-account/blob/767ef36bba88bdbc0c9fe3708a4290cabef4c376/contracts/GnosisSafe.sol#L190-L192

https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/rumpel-wallet/src/RumpelGuard.sol#L85
## Tool used

Manual Review

## Recommendation
add necessary logic to `RumpelGuard.checkAfterExecution()` and ensure that it reverts the tx if the transactions fails

**Comment by AuditorPraise** [comment]
@WangSecurity @jparklev  Hey, pls can i get a reason on why this was excluded?
so i can know if i should go ahead with my escalation
