### ISSUE TITLE
irresponsible - Malicious User may burn another users pTokens and redeem on their behalf

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-07-sense-points-marketplace-judging#94]
irresponsible

High

# Malicious User may burn another users pTokens and redeem on their behalf

### Summary

In PointTokenVault.sol there is a function that allows a user to claim p tokens, it can be observed below

https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/076bf833f4dc1418e93c8172e4a4110344f1c812/point-tokenization-vault/contracts/PointTokenVault.sol#L142
```solidity
    function claimPTokens(Claim calldata _claim, address _account, address _receiver) public {
        bytes32 pointsId = _claim.pointsId;

        bytes32 claimHash = keccak256(abi.encodePacked(_account, pointsId, _claim.totalClaimable));
        _verifyClaimAndUpdateClaimed(_claim, claimHash, _account, claimedPTokens);

        if (address(pTokens[pointsId]) == address(0)) {
            revert PTokenNotDeployed();
        }

        if (_account != _receiver && !trustedClaimers[_account][_receiver]) {
            revert NotTrustedClaimer();
        }

        uint256 pTokenFee = FixedPointMathLib.mulWadUp(_claim.amountToClaim, mintFee);
        pTokenFeeAcc[pointsId] += pTokenFee;

        pTokens[pointsId].mint(_receiver, _claim.amountToClaim - pTokenFee); // Subtract mint fee.

        emit PTokensClaimed(_account, _receiver, pointsId, _claim.amountToClaim, pTokenFee);
    }
```

The problem occurs because the function allows anyone to call this function for an account that is not theirs, this is evident in the snippet from the code below
```solidity
        if (_account != _receiver && !trustedClaimers[_account][_receiver]) {
            revert NotTrustedClaimer();
        }
```
This logic allows a malicious user to claim for the `account` that is not theirs as long as the receiver address is  the same as the `account`.

Why is this problematic you may ask? It is problematic because a user may not want the ptokens to be claim to that account, after all there does exist `trustedClaimers` that a user may add in order to claim ptokens on another address besides `account`. The reason this is problematic is because the account owner may have wanted the ptokens to be minted to that account for multiple reason for example, in case he lost access to the main account, the account is a contract that cannot handle the logic of using/ interacting with pTokens. Overall allowing a random user to take control of the destination of another user is a horrible idea.

Additionally since the fees are rounded up when claiming, the malicious user can also claim in a way to have more fees be collected by claiming in multiple tx instead of claiming just once. Because the fee calculation is rounded up, if we claim in small increments 1000 times, we will have a rounded up fee 1000 times, so 1000 more wei of fee. The attacker can split the increments even more to increase the damage

What is more damaging, the attacker can claim for account in 1 wei increments and essentially burn his ptokens, let us look at the fee logic inside the code snippet...

```solidity
        uint256 pTokenFee = FixedPointMathLib.mulWadUp(_claim.amountToClaim, mintFee);
        pTokenFeeAcc[pointsId] += pTokenFee;

        pTokens[pointsId].mint(_receiver, _claim.amountToClaim - pTokenFee); // Subtract mint fee.
```

as we can see from the snippet, we round up and then we `pTokens[pointsId].mint(_receiver, _claim.amountToClaim - pTokenFee);`

This means that if an attacker mints in 1 wei increments, the fee will be 0 but then rounded up to 1. since the token fee is subtracted from `amountToClaim`, he will not mint anything but lower his amount to claim, essentially burning the pToken. This can be repeated by an attacker multiple times in order to Burn a large amount of anothers user's pToken mint.

### Root Cause

in `claimPTokens` functions a user can claim on behalf of another user even if he is not a trusted receiver/claimer.

### Internal pre-conditions

na

### External pre-conditions

na

### Attack Path

ATTACK PATH 1
1. A user has ptokens to claim
2. he has set a trustedClaimer that is his eoa because his main account is a contract that cannot handle/ is not coded to handle ptokens
3. a malicious user calls `claimPToken` of the User A  setting the receiver to user A's main address not the trusted receiver address
4. the ptokens are minted to User A's main account address without his consent
5. User A did not have a say of where his ptokens were sent and they are now stuck in his main address wallet, this was not his intent.

ATTACK PATH 2
1. User A , bob, has pTokens to claim
2. Malicious user B, alice claim on his behalf but does so in 1 wei increments
3. because the fee is rounded up then subtracted from the amount to claim, the amount available to claim/mint is lowered while nothing is actually minted to bob
4. alice does thing couple hundred times, and even thousands of times with a bot in order to burn bobs pTokens.

### Impact

there is 2 impact
1. a malicious user can send the ptokens to an account the owner did not wish to send to, this could be a contract that cannot handle the pTokens, the owner set a trusted receiver and his intention was to claim with that receiver address. The funds are moved against his will
2. A malicious user can claim in a non optimized way on behalf of the owner to incur alot more fees and in extreme cases burn his ptokens essentially.

### Mitigation

Do not allow others to claim ptokens for other accounts even if the receiver is that account.

A fix like this should work

claimPToken function ln 152
```solidity
        if (msg.sender != _receiver && !trustedClaimers[_account][_receiver]) {
            revert NotTrustedClaimer();
```
in the if statment change `_account` to `msg.sender` to ensure a malicious user cannot claim on behalf of another user.

**Comment by ArnieSec** [comment]
Escalate

This issue should be valid.
The report shows how a user can essentially burn another users funds by following the following steps...

> 1. User A , bob, has pTokens to claim
> 2. Malicious user B, alice claim on his behalf but does so in 1 wei increments
> 3. because the fee is rounded up then subtracted from the amount to claim, the amount available to claim/mint is lowered while  > nothing is actually minted to bob
> 4. alice does thing couple hundred times, and even thousands of times with a bot in order to burn bobs pTokens.

> This means that if an attacker mints in 1 wei increments, the fee will be 0 but then rounded up to 1. since the token fee is subtracted from amountToClaim, he will not mint anything but lower his amount to claim, essentially burning the pToken. This can be repeated by an attacker multiple times in order to Burn a large amount of anothers user's pToken mint.

The attack will be costly but this should still classify this issue as medium.

From sherlock rules of what is considered a valid medium
> Causes a loss of funds but requires certain external conditions or specific states, or a loss is highly constrained. The losses must exceed small, finite amount of funds, and any amount relevant based on the precision or significance of the loss.

Since the attack can theoretically burn the full amount for another user this should classify it as a valid medium.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This issue should be valid.
> The report shows how a user can essentially burn another users funds by following the following steps...
> 
> > 1. User A , bob, has pTokens to claim
> > 2. Malicious user B, alice claim on his behalf but does so in 1 wei increments
> > 3. because the fee is rounded up then subtracted from the amount to claim, the amount available to claim/mint is lowered while  > nothing is actually minted to bob
> > 4. alice does thing couple hundred times, and even thousands of times with a bot in order to burn bobs pTokens.
> 
> > This means that if an attacker mints in 1 wei increments, the fee will be 0 but then rounded up to 1. since the token fee is subtracted from amountToClaim, he will not mint anything but lower his amount to claim, essentially burning the pToken. This can be repeated by an attacker multiple times in order to Burn a large amount of anothers user's pToken mint.
> 
> The attack will be costly but this should still classify this issue as medium.
> 
> From sherlock rules of what is considered a valid medium
> > Causes a loss of funds but requires certain external conditions or specific states, or a loss is highly constrained. The losses must exceed small, finite amount of funds, and any amount relevant based on the precision or significance of the loss.
> 
> Since the attack can theoretically burn the full amount for another user this should classify it as a valid medium. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
About the first impact from the attack path 1:
This is the mistake of user A and that their contract cannot extract tokens. Hence, I believe this impact is invalid.

About the second impact from attack path 2:
Firstly, I'm not even sure "Malicious user B, alice claim on his behalf but does so in 1 wei increments" is possible, because when calling `claimPTokens` you don't input an amount to claim, secondly, the claim point should be verified with the merkle tree. Moreover, as I understand the loss would be extremely small in that case, because the rounding would be only 1 wei. Additionally, I don't think repeating this 1000 times, it's still only 1000 wei. Now imagine how costly it would be on Ethereum mainnet.

Hence, I believe this is low severity and should remain is at is. Planning to reject the escalation.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ArnieSec](https://github.com/sherlock-audit/2024-07-sense-points-marketplace-judging/issues/94/#issuecomment-2328285828): rejected
