### ISSUE TITLE
dimulski - If a user claims to a trusted claimer, he will have to pay more fees

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-07-sense-points-marketplace-judging#96]
dimulski

Medium

# If a user claims to a trusted claimer, he will have to pay more fees

### Summary

The [claimPTokens()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L142-L162) function allows users to claim their pTokens, and mint them to a specific address. The protocol implements a so called "fee on the borders" strategy, via the readme: *We chose a "fee on the borders" strategy in the vault where users are only charged for redemption if they redeem in excess of what they minted, pToken wise.* However if the **_receiver** parameter is different than the **_account**, the **_receiver** will be minted the pTokens, pay a minting fee, and when the receiver tries to redeem his pTokens via the [redeemRewards()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L172-L226) function he will have to pay a redeeming fee as well. The [claimPTokens()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L142-L162) function internally calls the the [_verifyClaimAndUpdateClaimed()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L271-L296) function where the  **claimedPTokens** mapping is updated for the **_account** parameter provided in the [claimPTokens()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L142-L162) function, not the **_receiver** . The  **claimedPTokens** mapping is used in 
the [redeemRewards()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L172-L226) function to determine how much pTokens a user can redeem without paying a redeeming fee. If the pTokens are merkle based the **_receiver** won't be able to directly claim the tokens as well, as he won't have the so called redemption rights, which are checked on the following line in the [redeemRewards()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L172-L226) function:
```solidity
        if (isMerkleBased) {
            // If it's merkle-based, only those callers with redemption rights can redeem their point token for rewards.

            bytes32 claimHash =
                keccak256(abi.encodePacked(REDEMPTION_RIGHTS_PREFIX, msg.sender, pointsId, _claim.totalClaimable));
            _verifyClaimAndUpdateClaimed(_claim, claimHash, msg.sender, claimedRedemptionRights);
        }
```
Keep in mind that the [claimPTokens()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L142-L162) function is permissionless, and everybody can call it and set the **_account** and **_receiver** parameters, if the owner of **_account** has approved the **_receiver** via the [trustClaimer()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L164-L167) function. The approval is for all pTokens not just one, if for some reason the owner of the **_account** address has set the **_receiver** address as a trustedClaimer, intending to use it to claim pTokenA, but the owner of **_account** can also claim pTokens B which are merkle based, another user can call the [claimPTokens()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L142-L162) function for pTokens B and claim them to the **_receiver** address.
### Root Cause

In the [_verifyClaimAndUpdateClaimed()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L271-L296) function which is internally called by the the [claimPTokens()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L142-L162) function **claimedPTokens** mapping is updated for the **_account** parameter provided in the [claimPTokens()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L142-L162) function, not the **_receiver** .

### Internal pre-conditions
1. User A calls the [trustClaimer()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L164-L167) function and sets User B as a trusted claimer.
2. User A calls the [claimPTokens()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L142-L162) function in order to claim all of his pTokens and provides the address of User A as the **_account** parameter, and the address of User B as the **_receiver** parameter.

### Impact

If a user sets another account that can receive his pTokens in the **trustedClaimers** mapping, and claims his pTokens to that account, the trusted claimer account will have to pay an addition redeeming fee, leading to a loss of rewards for the user. If pTokens are merkle based, the trusted claimer won't be able to redeem his rewards via the [redeemRewards()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L172-L226) function.

### Mitigation
Use the **_receiver** parameter provided in the [claimPTokens()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L142-L162) function to update the laimedPTokens** mapping in the  [_verifyClaimAndUpdateClaimed()](https://github.com/sherlock-audit/2024-07-sense-points-marketplace/blob/main/point-tokenization-vault/contracts/PointTokenVault.sol#L271-L296) function. Implement a way to check if the pTokens are merkle based,  and if so don't allow users to set the **_receiver** parameter to a different address than the **_account** parameter.

**Comment by AtanasDimulski** [comment]
Escalate,
This report describes a discrepancy in the intended fees that users should pay if they claim to another account. If a user utilizes a trustedClaimer he will have to pay more fees than he is supposed to. As per this [sponsor comment](https://discordapp.com/channels/812037309376495636/1277643765133348956/1280803011047985265):  *The intent of setting a "trusted claimer" is so that you can set another wallet you own to receive pTokens. Without this functionality, pToken holders earning points in a rumpel wallet, would need to claim directly to their rumpel wallet. Given the restrictions in place on the rumpel wallet, this would be quite inconvenient and they would almost definitely transfer the pTokens immediately to another wallet*. I believe medium severity is appropriate.

**Comment by sherlock-admin3** [comment]
> Escalate,
> This report describes a discrepancy in the intended fees that users should pay if they claim to another account. If a user utilizes a trustedClaimer he will have to pay more fees than he is supposed to. As per this [sponsor comment](https://discordapp.com/channels/812037309376495636/1277643765133348956/1280803011047985265):  *The intent of setting a "trusted claimer" is so that you can set another wallet you own to receive pTokens. Without this functionality, pToken holders earning points in a rumpel wallet, would need to claim directly to their rumpel wallet. Given the restrictions in place on the rumpel wallet, this would be quite inconvenient and they would almost definitely transfer the pTokens immediately to another wallet*. I believe medium severity is appropriate. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
@AtanasDimulski I'm afraid I'm a bit lost, so would like to confirm if my understanding is correct. You're saying that you'll have to pay more fees than you should do, i.e. you would pay twice more (1 time yourself and 1 time the `receive`), correct?

**Comment by 0xsimao** [comment]
This is a design choice, the receiver can opt to sell the tokens in the open market or give back the tokens to the `account` for redemption. The receiver only pays the fees if it wants to. Even if it pays the fees, the `account` retains the `claimed` amount, which can be used to spare fees in the future.

**Comment by AtanasDimulski** [comment]
Hey @WangSecurity, when a user mints he pays a minting fee, then he doesn't have to pay a redemption fee for the amount he minted, however, if he claims to a trusted account, the trusted account will have to pay the redemptions fee as well. This results in both the minting and redemption fees being paid, which is a loss of funds for the user. If a user decides to claim tokens to a trusted account it doesn't make much sense to then send the tokens to 10 different accounts, it is pretty logical that if you claim to a trusted account you are going to redeem from that trusted account. As per the sponsor: *For this reason, we allow the rumpel wallet owner to set another wallet as an "approvedClaimer" to receive the pTokens to make their life easier.*, I don't know how paying double fees is a correct design choice, there is a loss of funds for the user due to this design choice.

**Comment by 0xsimao** [comment]
@AtanasDimulski there is no loss of funds, the trusted claimer can send the tokens back to the account and redeem without fee. Again, this is a design choice of the protocol. Someone has to aquire the ability to redeem without fees, the protocol chose to always give the account this ability.

**Comment by WangSecurity** [comment]
I'll agree with @0xsimao on this one. Still the user can avoid paying the fees if they want to and *"For this reason, we allow the rumpel wallet owner to set another wallet as an "approvedClaimer" to receive the pTokens to make their life easier."* doesn't necessarily mean the approved claimer shouldn't pay the fees. Technically, the approved claimer didn't mint anything, that's why they have to pay the redemption fee.

Even though it may seem a non-obvious design decision, it still is. Hence, planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [AtanasDimulski](https://github.com/sherlock-audit/2024-07-sense-points-marketplace-judging/issues/96/#issuecomment-2329690618): rejected
